name: Create Node Workspaces 1 Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'node/workspaces/src/test-workspace-1/**'

jobs:
  create_label:
    name: Create Version Label
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate action.yml against GitHub Action schema
        uses: sergey-koryshev/bump-version@dev/add-ci
        with:
          project-type: Node
          workspace-name: test-workspace-1
          version-configuration-path: version-configuration.json
          override-increment-parts: "Minor,Patch"