name: Create Node Workspaces 1 Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'node/workspaces/src/test-workspace-1/**'

jobs:
  create_label:
    name: Create Version Label
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: NPM authentication
        run: |
          npm config set //npm.pkg.github.com/:_authToken "$NPM_TOKEN"
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment Version
        uses: sergey-koryshev/bump-version@dev/add-ci
        with:
          project-type: Node
          root-path: node/workspaces
          workspace-name: test-workspace-1
          version-configuration-path: version-configuration.json
          override-increment-parts: "Minor,Patch"

      - name: Clean up .npmrc
        if: always()
        run: npm config delete //npm.pkg.github.com/:_authToken