name: Create Node Workspaces Version Label

concurrency: versioning

on:
  workflow_dispatch:

jobs:
  create_label:
    name: Create Version Label
    uses: sergey-koryshev/build-system/.github/workflows/create-version-label.yml@version-helper-v1.3.0
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      app-name: test-workspace-1
      project-type: Node
      root-path: node/workspaces
      workspace-name: test-workspace-1
      version-configuration-path: version-configuration.json
      scripts-ref: version-helper-v1.3.0