name: Create Node Workspaces 1 Version Label

concurrency: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'node/workspaces/src/test-workspace-1/**'

jobs:
  create_label:
    name: Create Version Label
    uses: sergey-koryshev/build-system/.github/workflows/create-version-label.yml@create-version-label-v1.4.2
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_PAT }}
    with:
      app-name: test-workspace-1
      project-type: Node
      root-path: node/workspaces
      workspace-name: test-workspace-1
      version-configuration-path: version-configuration.json
      scripts-ref: create-version-label-v1.4.2
